import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './app/**/*.{js,ts,jsx,tsx}',
    './components/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary': '#003426',
        'on-primary': '#ffffff',
        'primary-container': '#0f4c3a',
        'primary-fixed': '#b4efd6',
        'primary-fixed-dim': '#99d3ba',
        'on-primary-fixed': '#002117',
        'on-primary-fixed-variant': '#15503e',
        'on-primary-container': '#82bba4',
        'secondary': '#4e5e81',
        'on-secondary': '#ffffff',
        'secondary-container': '#c4d4fd',
        'secondary-fixed': '#d8e2ff',
        'secondary-fixed-dim': '#b6c6ef',
        'on-secondary-fixed': '#081b3a',
        'on-secondary-fixed-variant': '#364768',
        'tertiary': '#4d1f1b',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#68342f',
        'on-tertiary-container': '#e69e96',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#f8f9ff',
        'on-background': '#0b1c30',
        'surface': '#f8f9ff',
        'surface-bright': '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-tint': '#306855',
        'on-surface': '#0b1c30',
        'surface-variant': '#d3e4fe',
        'on-surface-variant': '#404944',
        'outline': '#707974',
        'outline-variant': '#bfc9c3',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        'inverse-primary': '#99d3ba',
      },
      fontFamily: {
        'inter': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-metrics': ['48px', { lineHeight: '1.1', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '1', fontWeight: '700', letterSpacing: '0.05em' }],
      },
      spacing: {
        'base': '4px',
        'gutter': '16px',
        'margin-mobile': '16px',
        'margin-desktop': '32px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '24px',
        'touch-target-min': '48px',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'sm': '0.125rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
    },
  },
  plugins: [],
}
export default config
